services:
  caddy:
    image: caddy:2-alpine
    working_dir: /etc/caddy
    ports:
      - "8765:8765"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./terms:/etc/caddy/terms:ro
    restart: unless-stopped

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - "8764:8764"
    volumes:
      - .:/project
    working_dir: /project
    restart: unless-stopped
