services:
  caddy:
    image: caddy:2-alpine
    working_dir: /etc/caddy
    ports:
      - "8765:8765"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./terms:/etc/caddy/terms:ro
    restart: unless-stopped

  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - "8764:8764"
    volumes:
      - .:/mkdocs
    working_dir: /mkdocs
    restart: unless-stopped
    # NOTE: explicit --live-reload because of upstream Click bug
    # https://github.com/squidfunk/mkdocs-material/issues/8478
    # Can be removed when MkDocs/Click is fixed
    command: sh -c "mkdocs serve --livereload --dev-addr=0.0.0.0:8764"